src/components/common/Button/Button.style.ts
src/components/common/Button/index.tsx
src/components/common/GNB/index.tsx
src/styles/theme.ts

[Fix] 버튼 컴포넌트 수정

---

.gitignore
src/api/index.ts

[Dev] vercel-deploy 추가
<br />
- gitignore 수정
<br />
-

[Fix]  gitignore 수정

---

src/api/client/create.ts
src/components/ClientDetail/DownloadModal/index.tsx

<br />
- 엑셀파일 다운로드 수정
<br />
-

[Fix] 엑셀파일 다운로드 수정

---

index.html
src/components/CampaignGroupList/index.tsx
src/components/CreateCampaign/CreateCampaignCondition/CreateCampaignCondition.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/CustomerSetting/CustomerSetting.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/MessageSetting/MessageSetting.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/index.tsx
src/components/CreateCampaign/CustomerGroupModal/index.tsx
src/components/CreateCampaign/Header/Header.styles.ts
src/components/CreateCampaign/MessageList/CampaignMessage/index.tsx
src/components/CreateCampaign/MessageList/index.tsx
src/components/DetailCampaign/Analysis/index.tsx
src/components/DetailCampaign/CampaignInfo/index.tsx
src/components/DetailCampaign/CustomerGroupInfo/index.tsx
src/components/DetailCampaign/Header/Header.styles.ts
src/components/DetailCampaign/Header/index.tsx
src/components/DetailCampaign/SendMessage/SendMessage.styles.ts
src/components/common/GNB/index.tsx
src/layouts/Layout.tsx
src/pages/CampaignGroups.tsx
src/pages/DetailCampaign.tsx
src/types/campaign.d.ts
src/utils/numberWithComma.ts

<br />
- 숫자 3자리 마다 콤마 찍기
- 캠페인 생성 페이지 바이트 수 색상 변경
- 캠페인 헤더 위치 조정
- 캠페인 상세 페이지 메세지 줄 넘침 방지
- 캠페인 상세 인원수 , 메세지 할당 수 변경
- 캠페인 헤더에 캠페인 명 보여주기
<br />
-

[Feat]campaign

---

index.html
src/components/CampaignGroupList/index.tsx
src/components/CreateCampaign/CreateCampaignCondition/CreateCampaignCondition.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/CustomerSetting/CustomerSetting.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/MessageSetting/MessageSetting.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/index.tsx
src/components/CreateCampaign/CustomerGroupModal/index.tsx
src/components/CreateCampaign/Header/Header.styles.ts
src/components/CreateCampaign/MessageList/CampaignMessage/index.tsx
src/components/CreateCampaign/MessageList/index.tsx
src/components/DetailCampaign/Analysis/index.tsx
src/components/DetailCampaign/CampaignInfo/index.tsx
src/components/DetailCampaign/CustomerGroupInfo/index.tsx
src/components/DetailCampaign/Header/Header.styles.ts
src/components/DetailCampaign/Header/index.tsx
src/components/DetailCampaign/SendMessage/SendMessage.styles.ts
src/components/common/GNB/index.tsx
src/layouts/Layout.tsx
src/pages/CampaignGroups.tsx
src/pages/DetailCampaign.tsx
src/types/campaign.d.ts
src/utils/numberWithComma.ts

* [feat] numberWithComma
* [fix]캠페인 상세 메세지 넘침 방지
* [feat] 헤더 위치 조정
* [fix] 숫자에 점찍기
* [fix] 캠페인 생성 바이트 수 변경
* [fix] 고객 선택시 인원수 안나오는 문제 해결
* [fix] white-space nowrap 처리
* [fix] 캠페인 헤더에 캠페인 이름 보여주기
<br />
-
<br />
-

[Dev]campaign  상세 페이지 수정 (#41)

---

src/components/ClientCreate/index.tsx
src/components/ClientDetail/index.tsx
src/components/ClientGroup/list/index.tsx
src/components/CreateCampaign/Header/index.tsx
src/pages/ClientCreate.tsx
src/pages/ClientGroups.tsx
src/pages/CreateCampaign.tsx
src/routes/index.tsx
src/types/client.d.ts

<br />
- 고객그룹 캠페인 연결 
<br />
-

[Feat] 고객그룹 캠페인 연결 

---

src/components/CampaignGroupList/CampaginGroupList.ts
src/components/CampaignGroupList/index.tsx
src/components/CreateCampaign/CopyGroupModal/MessageListForModal/index.tsx
src/components/CreateCampaign/CreateCampaignCondition/SelectCopy/SelectCopy.stlyes.ts
src/components/CreateCampaign/CustomerGroupModal/index.tsx
src/components/CreateCampaign/MessageList/CampaignMessage/index.tsx
src/components/CreateCopy/CopyDeleteModal/index.tsx
src/components/CreateCopy/CopyListItem/index.tsx
src/components/CreateCopy/CreateCopyCondition/index.tsx
src/components/CreateCopy/SubmitModal/index.tsx
src/components/DetailCampaign/Analysis/index.tsx
src/components/DetailCampaign/Comment/Comment.styles.ts
src/components/DetailCampaign/Comment/index.tsx
src/components/DetailCampaign/CustomerGroupInfo/CustomerGroupInfo.styles.ts
src/components/DetailCampaign/CustomerGroupInfo/index.tsx
src/components/DetailCampaign/SendMessage/SendMessage.styles.ts
src/components/DetailCampaign/SendMessage/index.tsx
src/components/DetailCopy/CopyDetails/index.tsx
src/pages/CampaignGroups.tsx
src/pages/CopyGroups.tsx
src/pages/CreateCopy.tsx
src/pages/Redirect.tsx
src/quries/Copy/useCreateCopyGroupMutation.ts
src/routes/index.tsx
src/types/campaign.d.ts
src/types/copy.d.ts

<br />
- Redirect 페이지 추가
- 키워드 글자수 제한 추가
- 카피 리스트 삭제 시 모달 추가
- 카피 저장시 모달 추가
- 카피 상세에서 추가로  카피 생성시 최대 20개 넘을 경우 모달 추가
-  코멘트 글자 수 제한 추가
- 캠페인 생성 URL 줄 넘침 방지
- 캠페인 생성시 카피 선택 후 모달 닫으면 선택 한 값 초기화
<br />
-

[Fix] 그룹 및 캠페인 QA1차 반영

---

src/components/CampaignGroupList/CampaginGroupList.ts
src/components/CampaignGroupList/index.tsx
src/components/CreateCampaign/CopyGroupModal/MessageListForModal/index.tsx
src/components/CreateCampaign/CreateCampaignCondition/SelectCopy/SelectCopy.stlyes.ts
src/components/CreateCampaign/CustomerGroupModal/index.tsx
src/components/CreateCampaign/MessageList/CampaignMessage/index.tsx
src/components/CreateCopy/CopyDeleteModal/index.tsx
src/components/CreateCopy/CopyListItem/index.tsx
src/components/CreateCopy/CreateCopyCondition/index.tsx
src/components/CreateCopy/SubmitModal/index.tsx
src/components/DetailCampaign/Analysis/index.tsx
src/components/DetailCampaign/Comment/Comment.styles.ts
src/components/DetailCampaign/Comment/index.tsx
src/components/DetailCampaign/CustomerGroupInfo/CustomerGroupInfo.styles.ts
src/components/DetailCampaign/CustomerGroupInfo/index.tsx
src/components/DetailCampaign/SendMessage/SendMessage.styles.ts
src/components/DetailCampaign/SendMessage/index.tsx
src/components/DetailCopy/CopyDetails/index.tsx
src/pages/CampaignGroups.tsx
src/pages/CopyGroups.tsx
src/pages/CreateCopy.tsx
src/pages/Redirect.tsx
src/quries/Copy/useCreateCopyGroupMutation.ts
src/routes/index.tsx
src/types/campaign.d.ts
src/types/copy.d.ts

* [feat] Redirect 페이지 추가
* [fix] 키워드 글자수 제한 에러 수정
* [feat] 카피 submit 모달 추가
* [feat] 카피리스트 DeleteModal
* [feat] 카피 상세에서 최대 20개 넘을경우 모달 생성
* [feat] 카피 수정시 모달띄우기
* [fix]캠페인명 글자 넘침 방지
* [fix]코멘트에 글자수 제한 추가
* [fix]캠페인 상세 메세지 리스트 UI변경
* [fix] url 줄넘침 방지
* [fix] 카피 선택 후 모달 닫힐때 선택 값 비우기
<br />
-
<br />
-

[Fix] 그룹 및 캠페인 QA1차 반영 (#46)

---

src/pages/DetailCopy.tsx

[feat] 카피 상세 저장시 모달 생성

---

src/pages/DetailCopy.tsx

[feat] 카피 상세 저장시 모달 생성 (#50)

---

src/components/CreateCampaign/CopyGroupModal/CopyGroupListForModal/index.tsx
src/components/CreateCampaign/CopyGroupModal/MessageListForModal/index.tsx
src/components/CreateCampaign/CreateCampaignCondition/MessageSetting/MessageSetting.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/SelectCopy/index.tsx
src/components/CreateCampaign/CustomerGroupModal/index.tsx
src/components/CreateCampaign/Header/index.tsx
src/components/CreateCampaign/MessageList/MessageList.stlyes.ts
src/components/CreateCampaign/MessageList/index.tsx
src/components/CreateCampaign/SubmitModal/index.tsx
src/components/CreateCopy/CreateCopyCondition/CreateCopyCondition.styles.ts
src/components/CreateCopy/CreateCopyCondition/index.tsx
src/components/CreateCopy/EditModal/index.tsx
src/components/DetailCopy/CopyDetails/CopyDetail.stlyes.ts
src/components/DetailCopy/CopyDetails/index.tsx
src/components/common/DropDown/DropDown.styles.ts
src/components/common/DropDown/index.tsx
src/components/common/ListCount/index.tsx
src/components/common/Modal/Modal.styles.ts
src/components/common/Modal/index.tsx
src/layouts/Layout.tsx
src/pages/CampaignGroups.tsx
src/pages/CopyGroups.tsx
src/pages/DetailCopy.tsx
src/quries/Campaign/useCreateCampaignMutation.ts
src/store/campaignConditionState.ts

[Fix] 캠페인 및 카피 UI 수정

---

src/components/common/GNB/index.tsx
src/layouts/Layout.tsx

<br />
- GNB 선택시 색상 변경
- sticky 적용
<br />
-

[feat] GNB선택시 색상 변경, sticky적용

---

src/components/ClientCreate/index.tsx
src/components/PreventModal/index.tsx
src/components/common/GNB/index.tsx
src/layouts/Layout.tsx
src/pages/CreateCampaign.tsx
src/pages/CreateCopy.tsx
src/routes/index.tsx
src/utils/usePreventEvent.ts

[Feat] GNB 수정

---

src/api/client/create.ts
src/components/ClientCreate/index.tsx
src/components/ClientDetail/DownloadModal/index.tsx
src/components/ClientDetail/index.tsx
src/components/ClientGroup/group/Group.ts
src/components/ClientGroup/group/index.tsx
src/components/ClientGroup/list/ClientGroupList.ts
src/components/ClientGroup/list/index.tsx
src/quries/Client/useCreateClientGroupMutaion.ts
src/quries/Client/useCreateClientMutaion.ts
src/types/client.d.ts

[Feat] 파일 업로드 수정

---

src/components/ClientGroup/list/ClientGroupList.ts
src/components/CreateCampaign/Header/index.tsx
src/components/DetailCampaign/Header/index.tsx
src/pages/CreateCopy.tsx

[fix] 캠페인,카피 생성 후 뒤로가기 시 -1 이 아닌 라우트로 연결

---

src/components/ClientGroup/list/ClientGroupList.ts
src/components/CreateCampaign/CopyGroupModal/CopyListForModal/index.tsx
src/components/CreateCampaign/Header/index.tsx
src/components/DetailCampaign/Header/index.tsx
src/pages/CreateCopy.tsx

[Fix] 캠페인 생성 - 생성된 카피 수 수정

---

.github/workflows/actions.yml
src/components/CreateCampaign/CreateCampaignCondition/MessageContainer/MessageContainer.styles.ts
src/components/CreateCampaign/CreateCampaignCondition/MessageContainer/index.tsx
src/components/CreateCopy/CopyListItem/CopyListItem.styles.ts
src/components/CreateCopy/CopyListItem/index.tsx
src/components/DetailCampaign/Comment/Comment.styles.ts
src/components/DetailCampaign/Comment/index.tsx
src/components/common/PreventModal/index.tsx
src/pages/CreateCopy.tsx
src/pages/DetailCampaign.tsx

[Fix] 캠페인 상세 코멘트 , 캠페인 생성 발송 URL UI 수정

---

src/components/ClientGroup/group/index.tsx
src/components/ClientGroup/list/index.tsx
src/quries/Client/useClientLikeMutation.ts
src/store/clientListState.ts
src/types/client.d.ts

[Ref]즐겨찾기 기능 추가

---

src/components/ClientCreate/index.tsx
src/quries/Client/useCreateClientMutaion.ts
src/quries/Client/useCreateClientMutation.ts
src/store/clientListState.ts

<br />
- 고객 등록시 목록 등록
<br />
-

[Ref] 고객 등록시 목록 등록

---

.github/workflows/actions.yml
src/components/ClientCreate/index.tsx
src/quries/Client/useCreateClientMutaion.ts
src/quries/Client/useCreateClientMutation.ts
src/store/clientListState.ts

<br />
- 고객 등록시 목록 등록
<br />
-

[Dev] 고객 등록시 목록 등록

---

src/api/Campaign/index.ts
src/constants/mock/campaingMock.ts

[feat] 캠페인 목데이터 생성 (#90)

---

src/components/ServiceHome/Onboarding.tsx
src/components/common/GNB/index.tsx
src/pages/SignUp.tsx

[Fix] GNB 수정

---

src/api/Campaign/index.ts
src/constants/mock/campaingMock.ts

[Dev] GNB 수정

---

src/components/ClientCreate/FileModal.tsx
src/components/ClientCreate/index.tsx
src/components/ClientDetail/DeleteModal.tsx
src/components/common/Modal/index.tsx

모달이 나온 뒤에 스크롤이 사라지는 이슈가 있어서 return 문을 추가해서 해결했습니다.
<br />
-
<br />
-

[Fix] 스크롤 이슈로 모달 수정

---

src/components/SignUp/SignUpForm/index.tsx
src/components/common/LabelInput/LabelInput.styles.ts
src/components/common/LabelInput/index.tsx
src/pages/SignUp.tsx

[fix] 회원가임 폼 인풋에 value 추가
